name = "pingpanda"
compatibility_date = "2024-03-29"

# ✅ This is the correct output directory for Pages projects (Vercel static output)
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SITE_URL = "https://pingpanda-252.pages.dev"

[env.production]
ENV_MODE = "production"

[env.preview]
ENV_MODE = "preview"  # Optional override if needed
