name = "pingpanda"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SITE_URL = "https://pingpanda-252.pages.dev"

[env.production]
[env.production.vars]
ENV_MODE = "production"

[env.preview]
[env.preview.vars]
ENV_MODE = "preview"

