name = "pingpanda"
main = "src/server/index.ts"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm run build"
upload_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SITE_URL = "https://pingpanda-252.pages.dev"

[env.production]
ENV_MODE = "production"

[env.staging]
ENV_MODE = "staging"